name: ship_certification
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  signature: ^5.0.0

flutter:
  # assets:
  #   - assets/
  uses-material-design: true
